#!/usr/bin/env python3
"""
Fast HTTP status tester for all surge.sh deployments
"""

import subprocess
import json
from pathlib import Path
from datetime import datetime
from collections import defaultdict

SWARM_DIR = Path(__file__).parent

def get_all_sites():
    """Extract all sites from surge list"""
    try:
        result = subprocess.run(
            ["surge", "list"],
            capture_output=True,
            text=True,
            timeout=30
        )

        sites = []
        for line in result.stdout.split("\n"):
            if ".surge.sh" in line:
                parts = line.split()
                if parts:
                    domain = parts[0]
                    sites.append(domain)

        return sites
    except Exception as e:
        print(f"Error getting surge list: {e}")
        return []

def test_site(domain):
    """Test a single site with HTTP HEAD request"""
    url = f"https://{domain}"
    try:
        result = subprocess.run(
            ["curl", "-s", "-o", "/dev/null", "-w", "%{http_code}", "--connect-timeout", "3", url],
            capture_output=True,
            text=True,
            timeout=5
        )

        status_code = int(result.stdout.strip()) if result.stdout.strip() else 0
        return {
            "domain": domain,
            "url": url,
            "status_code": status_code,
            "status": "OK" if status_code == 200 else f"HTTP {status_code}",
            "category": "GREEN" if status_code == 200 else ("YELLOW" if 300 <= status_code < 400 else "RED")
        }
    except Exception as e:
        return {
            "domain": domain,
            "url": url,
            "status_code": 0,
            "status": f"ERROR: {str(e)[:50]}",
            "category": "RED"
        }

def main():
    print("[TEST AGENT] Starting comprehensive site health check...")
    print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

    # Get all sites
    print("[1/3] Fetching all deployed sites from Surge...")
    sites = get_all_sites()
    print(f"Found {len(sites)} deployed sites.\n")

    # Test each site
    print("[2/3] Testing all sites (this may take 2-3 minutes)...")
    results = []

    for i, site in enumerate(sites, 1):
        result = test_site(site)
        results.append(result)

        # Progress indicator
        if i % 50 == 0:
            green = sum(1 for r in results if r["category"] == "GREEN")
            print(f"  Tested {i}/{len(sites)} — {green} GREEN so far...")

    # Categorize results
    categories = defaultdict(list)
    for r in results:
        categories[r["category"]].append(r)

    green_count = len(categories["GREEN"])
    yellow_count = len(categories["YELLOW"])
    red_count = len(categories["RED"])

    print(f"\n[3/3] Generating report...")
    print(f"\n=== RESULTS ===")
    print(f"✓ GREEN (200 OK):     {green_count:3d}")
    print(f"⚠ YELLOW (3xx/other): {yellow_count:3d}")
    print(f"✗ RED (error/down):   {red_count:3d}")
    print(f"  TOTAL:              {len(results):3d}")
    print(f"  Health: {round(green_count / len(results) * 100, 1)}%\n")

    # Report
    report = f"""# Surge.sh Site Health Report
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Summary
- **Total Deployed:** {len(results)}
- **✓ GREEN (OK):** {green_count} ({round(green_count / len(results) * 100, 1)}%)
- **⚠ YELLOW:** {yellow_count}
- **✗ RED (Down):** {red_count}
- **Overall Health:** {round(green_count / len(results) * 100, 1)}%

## Status by Category

### ✓ GREEN Sites (All OK)
{green_count} sites returning 200 OK.

### ⚠ YELLOW Sites (Redirects/Other)
"""

    if yellow_count > 0:
        for r in sorted(categories["YELLOW"], key=lambda x: x["status_code"]):
            report += f"- {r['domain']} — {r['status']}\n"
    else:
        report += "None.\n"

    report += "\n### ✗ RED Sites (Errors/Down)\n"

    if red_count > 0:
        for r in sorted(categories["RED"], key=lambda x: x["domain"]):
            report += f"- {r['domain']} — {r['status']}\n"
    else:
        report += "✓ All sites operational!\n"

    report += f"\n---\nReport generated by Playwright Tester Agent\n"

    # Save report
    report_path = SWARM_DIR / "reports" / f"site_health_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    report_path.write_text(report)

    latest_path = SWARM_DIR / "reports" / "site_health_report_latest.md"
    latest_path.write_text(report)

    print(f"✓ Report saved: {report_path.name}\n")

    # Save JSON for processing
    json_path = SWARM_DIR / f"test_results_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    json_path.write_text(json.dumps({
        "timestamp": datetime.now().isoformat(),
        "total": len(results),
        "green": green_count,
        "yellow": yellow_count,
        "red": red_count,
        "results": results
    }, indent=2))

    print(f"✓ JSON data saved: {json_path.name}\n")

    return 0 if red_count == 0 else 1

if __name__ == "__main__":
    exit(main())
