#!/usr/bin/env python3
"""
PRINTMAXX QA Auto-Approver (compliance-first)
============================================

Goal:
  Keep PRINTMAXX moving 24/7 by auto-approving ONLY low-risk content that is
  explicitly disclosed as AI/virtual and passes compliance scanning.

Current scope (intentionally narrow):
  - Instagram carousels generated by AUTOMATIONS/carousel_factory.py

It will:
  - Scan OPS/CONTENT_QA_QUEUE/*.md
  - For eligible items in PENDING_REVIEW:
      - scan the source file with AUTOMATIONS/compliance_scanner.py
      - verify AI/virtual disclosure exists
      - mark QA status as APPROVED (reviewed_by: auto)
      - update LEDGER/CONTENT_QA_LOG.csv (best-effort)

It will NOT:
  - Post anything
  - Auto-approve other content types (threads/posts/emails/etc.)
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Tuple


BASE_DIR = Path(__file__).resolve().parent.parent
QA_DIR = BASE_DIR / "OPS" / "CONTENT_QA_QUEUE"
QA_LOG_CSV = BASE_DIR / "LEDGER" / "CONTENT_QA_LOG.csv"
STATE_DIR = BASE_DIR / "OPS" / "_state"
STATE_FILE = STATE_DIR / "qa_auto_approver.json"


def now_iso() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def _parse_front_matter(text: str) -> Tuple[Dict[str, str], str, List[str]]:
    """
    Very small YAML front-matter parser:
      - expects leading --- ... --- block
      - parses simple 'key: value' lines
    Returns: (meta, body, key_order)
    """
    lines = text.splitlines(True)
    if not lines or lines[0].strip() != "---":
        return {}, text, []

    end_idx = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            end_idx = i
            break
    if end_idx is None:
        return {}, text, []

    meta: Dict[str, str] = {}
    key_order: List[str] = []
    for raw in lines[1:end_idx]:
        s = raw.strip()
        if not s or s.startswith("#") or ":" not in s:
            continue
        k, v = s.split(":", 1)
        k = k.strip()
        v = v.strip()
        if not k:
            continue
        meta[k] = v
        if k not in key_order:
            key_order.append(k)

    body = "".join(lines[end_idx + 1 :])
    return meta, body, key_order


def _render_front_matter(meta: Dict[str, str], body: str, key_order: List[str]) -> str:
    keys = list(key_order)
    for k in meta.keys():
        if k not in keys:
            keys.append(k)

    out: List[str] = ["---\n"]
    for k in keys:
        if k in meta:
            out.append(f"{k}: {meta[k]}\n")
    out.append("---\n")
    if not body.startswith("\n"):
        out.append("\n")
    out.append(body)
    return "".join(out)


def _load_state() -> Dict[str, object]:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    if not STATE_FILE.exists():
        return {"version": 1, "approved": {}}
    try:
        payload = json.loads(STATE_FILE.read_text(encoding="utf-8"))
        if isinstance(payload, dict):
            payload.setdefault("version", 1)
            payload.setdefault("approved", {})
            if not isinstance(payload["approved"], dict):
                payload["approved"] = {}
            return payload
    except Exception:
        pass
    return {"version": 1, "approved": {}}


def _save_state(state: Dict[str, object]) -> None:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _is_eligible(meta: Dict[str, str], source_path: Path) -> Tuple[bool, str]:
    platform = (meta.get("platform") or "").strip().lower()
    ctype = (meta.get("content_type") or "").strip().lower()
    status = (meta.get("status") or "").strip().upper()
    style_ok = (meta.get("style_check_passed") or "").strip().lower() in {"true", "yes", "1"}

    if status != "PENDING_REVIEW":
        return False, "status_not_pending"
    if platform != "instagram" or ctype != "carousel":
        return False, "not_instagram_carousel"
    if not style_ok:
        return False, "style_check_failed"

    # Only auto-approve carousels produced by our factory directory.
    try:
        rel = source_path.resolve().relative_to((BASE_DIR / "CONTENT" / "social" / "carousels").resolve())
        _ = rel  # unused; just a check
    except Exception:
        return False, "source_not_in_carousels_dir"

    return True, "eligible"


def _has_ai_disclosure(source_text: str) -> bool:
    # Require at least one of these patterns to reduce risk of "fake person" marketing.
    patterns = [
        r"(?i)\bvirtual\b.*\bai\b",
        r"(?i)\bai\b.*\bcreator\b",
        r"(?i)\bvirtual/ai creator\b",
        r"(?i)\bthis account is a virtual/ai creator\b",
    ]
    return any(re.search(p, source_text) for p in patterns)


def _scan_compliance(source_abs: str) -> List[Dict[str, str]]:
    # Import locally to avoid surprises if this file is used standalone.
    from compliance_scanner import ComplianceScanner

    scanner = ComplianceScanner(project_root=str(BASE_DIR))
    issues = scanner.scan_file(source_abs)
    return [i.to_dict() for i in issues]


def _update_qa_log(queue_rel: str, source_rel: str, new_status: str, decision: str) -> None:
    if not QA_LOG_CSV.exists():
        return

    rows: List[Dict[str, str]] = []
    try:
        with open(QA_LOG_CSV, "r", newline="", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
    except Exception:
        return

    updated = False
    for r in rows:
        if (r.get("queue_file") or "").strip() == queue_rel or (r.get("source_file") or "").strip() == source_rel:
            r["status"] = new_status
            r["reviewed_date"] = datetime.now().isoformat()
            r["review_decision"] = decision
            updated = True
            break

    if not updated:
        # Best-effort append a minimal row.
        rows.append(
            {
                "source_file": source_rel,
                "queue_file": queue_rel,
                "platform": "",
                "content_type": "",
                "niche": "",
                "style_check_passed": "",
                "status": new_status,
                "routed_date": "",
                "reviewed_date": datetime.now().isoformat(),
                "review_decision": decision,
            }
        )

    # Preserve headers if present, otherwise write canonical.
    fieldnames = list(rows[0].keys()) if rows else [
        "source_file",
        "queue_file",
        "platform",
        "content_type",
        "niche",
        "style_check_passed",
        "status",
        "routed_date",
        "reviewed_date",
        "review_decision",
    ]

    try:
        with open(QA_LOG_CSV, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=fieldnames)
            w.writeheader()
            for r in rows:
                w.writerow(r)
    except Exception:
        return


def run(*, max_items: int = 10, dry_run: bool = False) -> int:
    QA_DIR.mkdir(parents=True, exist_ok=True)
    state = _load_state()
    approved_state = state.get("approved", {})
    if not isinstance(approved_state, dict):
        approved_state = {}
        state["approved"] = approved_state

    approved = 0
    scanned = 0

    # Newest first: helps "daily" content get approved quickly.
    qas = sorted(QA_DIR.glob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True)

    for qa_path in qas:
        if approved >= max_items:
            break

        rel_qa = str(qa_path.relative_to(BASE_DIR))
        if approved_state.get(rel_qa):
            continue

        try:
            raw = qa_path.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue

        meta, body, order = _parse_front_matter(raw)
        source_rel = (meta.get("source_file") or "").strip()
        if not source_rel:
            continue

        source_path = (BASE_DIR / source_rel).resolve()
        ok, reason = _is_eligible(meta, source_path)
        if not ok:
            continue

        if not source_path.exists():
            continue

        try:
            source_text = source_path.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue

        if not _has_ai_disclosure(source_text):
            continue

        scanned += 1
        issues = _scan_compliance(str(source_path))
        # Strict: any WARNING/CRITICAL blocks auto-approval.
        # This is intentionally conservative.
        bad = [i for i in issues if (i.get("severity") or "").upper() in {"CRITICAL", "WARNING"}]
        if bad:
            continue

        if dry_run:
            print(f"qa_auto_approver: would_approve={rel_qa} reason={reason}")
            approved_state[rel_qa] = {"status": "DRY_RUN", "at": now_iso(), "source": source_rel}
            approved += 1
            continue

        # Keep markdown body consistent with front matter status.
        body = re.sub(r"(?m)^\\*\\*Status:\\*\\*\\s*.*$", "**Status:** APPROVED", body)

        meta["status"] = "APPROVED"
        meta["reviewed_by"] = "auto"
        meta["reviewed_date"] = now_iso()
        if "reviewed_by" not in order:
            order.append("reviewed_by")
        if "reviewed_date" not in order:
            order.append("reviewed_date")

        updated_text = _render_front_matter(meta, body, order)
        try:
            qa_path.write_text(updated_text, encoding="utf-8")
        except Exception:
            continue

        approved_state[rel_qa] = {"status": "APPROVED", "at": now_iso(), "source": source_rel}
        _update_qa_log(rel_qa, source_rel, "APPROVED", "APPROVED_AUTO")
        approved += 1

    _save_state(state)
    print(f"qa_auto_approver: scanned={scanned} approved={approved}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tick", action="store_true", help="Run auto-approval pass")
    ap.add_argument("--max", type=int, default=10)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if args.tick:
        return run(max_items=max(1, args.max), dry_run=args.dry_run)
    ap.print_help()
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
