export const COLORS = {
  primary: '#10B981',
  primaryDark: '#059669',
  primaryLight: '#6EE7B7',
  secondary: '#F59E0B',
  secondaryDark: '#D97706',
  accent: '#FFD93D',
  background: '#0F172A',
  surface: '#1E293B',
  surfaceLight: '#334155',
  text: '#F8FAFC',
  textSecondary: '#94A3B8',
  textMuted: '#64748B',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
  border: '#334155',
};

export const SOCIAL_PROOF = "Join 10,000+ optimizing their biology";

export const ONBOARDING_GOALS = [
  { id: 'longevity', label: 'Longevity', icon: 'leaf-outline' },
  { id: 'energy', label: 'Energy', icon: 'flash-outline' },
  { id: 'focus', label: 'Focus', icon: 'eye-outline' },
  { id: 'recovery', label: 'Recovery', icon: 'fitness-outline' },
  { id: 'weight', label: 'Weight Loss', icon: 'scale-outline' },
] as const;

export const PROTOCOL_CATEGORIES = [
  'fasting',
  'cold',
  'heat',
  'light',
  'supplements',
  'movement',
  'sleep',
] as const;

export const DEFAULT_PROTOCOLS = [
  {
    id: 'fasting',
    name: 'Intermittent Fasting',
    category: 'fasting',
    icon: 'timer-outline',
    unit: 'hours',
    dailyGoal: 16,
    description: 'Track your fasting windows for metabolic health',
    isPremium: false,
  },
  {
    id: 'cold',
    name: 'Cold Exposure',
    category: 'cold',
    icon: 'snow-outline',
    unit: 'minutes',
    dailyGoal: 3,
    description: 'Cold showers, ice baths, or cold plunges',
    isPremium: false,
  },
  {
    id: 'sleep',
    name: 'Sleep',
    category: 'sleep',
    icon: 'moon-outline',
    unit: 'hours',
    dailyGoal: 8,
    description: 'Log your sleep duration for recovery optimization',
    isPremium: false,
  },
  {
    id: 'redlight',
    name: 'Red Light Therapy',
    category: 'light',
    icon: 'sunny-outline',
    unit: 'minutes',
    dailyGoal: 15,
    description: 'Track red/NIR light exposure sessions',
    isPremium: false,
  },
  {
    id: 'supplements',
    name: 'Supplements',
    category: 'supplements',
    icon: 'medical-outline',
    unit: 'count',
    dailyGoal: 5,
    description: 'Log your daily supplement stack',
    isPremium: false,
  },
  {
    id: 'movement',
    name: 'Movement',
    category: 'movement',
    icon: 'walk-outline',
    unit: 'minutes',
    dailyGoal: 30,
    description: 'Track exercise, walks, and active minutes',
    isPremium: false,
  },
  {
    id: 'sauna',
    name: 'Sauna',
    category: 'heat',
    icon: 'flame-outline',
    unit: 'minutes',
    dailyGoal: 20,
    description: 'Heat therapy for cardiovascular health',
    isPremium: true,
  },
  {
    id: 'breathwork',
    name: 'Breathwork',
    category: 'movement',
    icon: 'cloud-outline',
    unit: 'minutes',
    dailyGoal: 10,
    description: 'Wim Hof, box breathing, and more',
    isPremium: true,
  },
  {
    id: 'sunlight',
    name: 'Morning Sunlight',
    category: 'light',
    icon: 'sunny-outline',
    unit: 'minutes',
    dailyGoal: 10,
    description: 'Morning light exposure for circadian health',
    isPremium: true,
  },
  {
    id: 'grounding',
    name: 'Grounding',
    category: 'movement',
    icon: 'earth-outline',
    unit: 'minutes',
    dailyGoal: 20,
    description: 'Earthing and barefoot time',
    isPremium: true,
  },
] as const;

export const LEARN_ARTICLES = [
  {
    id: 'getting-started',
    title: 'Getting Started with Biohacking',
    category: 'Getting Started',
    readTime: 5,
    isPremium: false,
    featured: true,
    excerpt: 'Your complete guide to beginning your optimization journey.',
  },
  {
    id: 'fasting-101',
    title: 'Intermittent Fasting 101',
    category: 'Protocol Deep-Dives',
    readTime: 8,
    isPremium: false,
    featured: false,
    excerpt: 'The science of time-restricted eating and how to do it right.',
  },
  {
    id: 'cold-exposure',
    title: 'Cold Exposure Benefits',
    category: 'Protocol Deep-Dives',
    readTime: 6,
    isPremium: false,
    featured: false,
    excerpt: 'Why deliberate cold is one of the most powerful health tools.',
  },
  {
    id: 'protocol-stacking',
    title: 'Protocol Stacking Guide',
    category: 'Stacking Guide',
    readTime: 10,
    isPremium: true,
    featured: false,
    excerpt: 'How to combine protocols for maximum benefit.',
  },
  {
    id: 'sleep-optimization',
    title: 'Sleep Optimization Masterclass',
    category: 'Protocol Deep-Dives',
    readTime: 12,
    isPremium: true,
    featured: false,
    excerpt: 'Advanced strategies for restorative sleep.',
  },
  {
    id: 'supplement-stack',
    title: 'Longevity Supplement Stack',
    category: 'Science',
    readTime: 15,
    isPremium: true,
    featured: false,
    excerpt: 'Evidence-based supplements for healthspan extension.',
  },
];

export const TIPS_OF_THE_DAY = [
  "Get 10+ minutes of morning sunlight within 30 minutes of waking for better sleep tonight.",
  "Try ending your shower with 30 seconds of cold water to boost alertness and mood.",
  "A 16-hour fast is easier than you think: stop eating at 8pm, break fast at noon.",
  "Consistent sleep and wake times matter more than total sleep duration.",
  "Walking after meals improves blood sugar response by up to 30%.",
  "Red light therapy works best on clean, dry skin without sunscreen.",
  "Magnesium before bed can improve sleep quality and muscle recovery.",
  "Even 2 minutes of cold exposure triggers beneficial hormetic stress.",
];

export const ACHIEVEMENTS = [
  { id: 'first-log', name: 'First Log', description: 'Log your first protocol', icon: 'star-outline' },
  { id: 'week-streak', name: 'Week Warrior', description: '7-day streak', icon: 'flame-outline' },
  { id: 'month-streak', name: 'Monthly Master', description: '30-day streak', icon: 'trophy-outline' },
  { id: 'cold-beginner', name: 'Ice Curious', description: '10 cold sessions', icon: 'snow-outline' },
  { id: 'fasting-pro', name: 'Fasting Pro', description: '50 fasting sessions', icon: 'timer-outline' },
  { id: 'all-protocols', name: 'Protocol Pioneer', description: 'Try all protocols', icon: 'ribbon-outline' },
];
